[package]
name = "rg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = "0.4.8"
thiserror = "1.0"
clap = "2.33"
regex = "1.5"
rayon = "1.5"
colored = "2.0"
